name: PR - Tests

on:
  pull_request: {}
  workflow_dispatch:



jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      checks: write          # para publicar el reporte en la PR
      pull-requests: write   # para comentar resumen de tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
       

      - name: Install deps
        run: npm ci

      # Ejecuta los tests en modo "run"  y genera JUnit
      - name: Run unit tests
        run: |
          set -o pipefail
          mkdir -p reports
            npx vitest --run --reporter=default --reporter=junit --outputFile=reports/junit.xml 2>&1 | tee tests.log

      # Publica un resumen visible en la PR (usar reporter JUnit)
      - name: Publish unit test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "reports/**/*.xml"

      # Guarda el log crudo si fallaron los tests 
      - name: Upload test log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: tests.log
